// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: facerec.proto

package facerec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Channels      int32                  `protobuf:"varint,4,opt,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageData) Reset() {
	*x = ImageData{}
	mi := &file_facerec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageData) ProtoMessage() {}

func (x *ImageData) ProtoReflect() protoreflect.Message {
	mi := &file_facerec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageData.ProtoReflect.Descriptor instead.
func (*ImageData) Descriptor() ([]byte, []int) {
	return file_facerec_proto_rawDescGZIP(), []int{0}
}

func (x *ImageData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ImageData) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageData) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageData) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

type ExtractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *ImageData             `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_facerec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_facerec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_facerec_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractRequest) GetImage() *ImageData {
	if x != nil {
		return x.Image
	}
	return nil
}

type Face struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Score         float32                `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`
	Feature       []float32              `protobuf:"fixed32,6,rep,packed,name=feature,proto3" json:"feature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Face) Reset() {
	*x = Face{}
	mi := &file_facerec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Face) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Face) ProtoMessage() {}

func (x *Face) ProtoReflect() protoreflect.Message {
	mi := &file_facerec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Face.ProtoReflect.Descriptor instead.
func (*Face) Descriptor() ([]byte, []int) {
	return file_facerec_proto_rawDescGZIP(), []int{2}
}

func (x *Face) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Face) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Face) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Face) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Face) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Face) GetFeature() []float32 {
	if x != nil {
		return x.Feature
	}
	return nil
}

type ExtractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Faces         []*Face                `protobuf:"bytes,1,rep,name=faces,proto3" json:"faces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_facerec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_facerec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_facerec_proto_rawDescGZIP(), []int{3}
}

func (x *ExtractResponse) GetFaces() []*Face {
	if x != nil {
		return x.Faces
	}
	return nil
}

type CompareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feature1      []float32              `protobuf:"fixed32,1,rep,packed,name=feature1,proto3" json:"feature1,omitempty"`
	Feature2      []float32              `protobuf:"fixed32,2,rep,packed,name=feature2,proto3" json:"feature2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareRequest) Reset() {
	*x = CompareRequest{}
	mi := &file_facerec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareRequest) ProtoMessage() {}

func (x *CompareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_facerec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareRequest.ProtoReflect.Descriptor instead.
func (*CompareRequest) Descriptor() ([]byte, []int) {
	return file_facerec_proto_rawDescGZIP(), []int{4}
}

func (x *CompareRequest) GetFeature1() []float32 {
	if x != nil {
		return x.Feature1
	}
	return nil
}

func (x *CompareRequest) GetFeature2() []float32 {
	if x != nil {
		return x.Feature2
	}
	return nil
}

type CompareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Similarity    float32                `protobuf:"fixed32,1,opt,name=similarity,proto3" json:"similarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareResponse) Reset() {
	*x = CompareResponse{}
	mi := &file_facerec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareResponse) ProtoMessage() {}

func (x *CompareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_facerec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareResponse.ProtoReflect.Descriptor instead.
func (*CompareResponse) Descriptor() ([]byte, []int) {
	return file_facerec_proto_rawDescGZIP(), []int{5}
}

func (x *CompareResponse) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

var File_facerec_proto protoreflect.FileDescriptor

const file_facerec_proto_rawDesc = "" +
	"\n" +
	"\rfacerec.proto\x12\afacerec\"i\n" +
	"\tImageData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1a\n" +
	"\bchannels\x18\x04 \x01(\x05R\bchannels\":\n" +
	"\x0eExtractRequest\x12(\n" +
	"\x05image\x18\x01 \x01(\v2\x12.facerec.ImageDataR\x05image\"\x80\x01\n" +
	"\x04Face\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x02R\x05score\x12\x18\n" +
	"\afeature\x18\x06 \x03(\x02R\afeature\"6\n" +
	"\x0fExtractResponse\x12#\n" +
	"\x05faces\x18\x01 \x03(\v2\r.facerec.FaceR\x05faces\"H\n" +
	"\x0eCompareRequest\x12\x1a\n" +
	"\bfeature1\x18\x01 \x03(\x02R\bfeature1\x12\x1a\n" +
	"\bfeature2\x18\x02 \x03(\x02R\bfeature2\"1\n" +
	"\x0fCompareResponse\x12\x1e\n" +
	"\n" +
	"similarity\x18\x01 \x01(\x02R\n" +
	"similarity2\x8d\x01\n" +
	"\x0fFaceRecognition\x12<\n" +
	"\aExtract\x12\x17.facerec.ExtractRequest\x1a\x18.facerec.ExtractResponse\x12<\n" +
	"\aCompare\x12\x17.facerec.CompareRequest\x1a\x18.facerec.CompareResponseB\x11Z\x0ffacerec/facerecb\x06proto3"

var (
	file_facerec_proto_rawDescOnce sync.Once
	file_facerec_proto_rawDescData []byte
)

func file_facerec_proto_rawDescGZIP() []byte {
	file_facerec_proto_rawDescOnce.Do(func() {
		file_facerec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_facerec_proto_rawDesc), len(file_facerec_proto_rawDesc)))
	})
	return file_facerec_proto_rawDescData
}

var file_facerec_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_facerec_proto_goTypes = []any{
	(*ImageData)(nil),       // 0: facerec.ImageData
	(*ExtractRequest)(nil),  // 1: facerec.ExtractRequest
	(*Face)(nil),            // 2: facerec.Face
	(*ExtractResponse)(nil), // 3: facerec.ExtractResponse
	(*CompareRequest)(nil),  // 4: facerec.CompareRequest
	(*CompareResponse)(nil), // 5: facerec.CompareResponse
}
var file_facerec_proto_depIdxs = []int32{
	0, // 0: facerec.ExtractRequest.image:type_name -> facerec.ImageData
	2, // 1: facerec.ExtractResponse.faces:type_name -> facerec.Face
	1, // 2: facerec.FaceRecognition.Extract:input_type -> facerec.ExtractRequest
	4, // 3: facerec.FaceRecognition.Compare:input_type -> facerec.CompareRequest
	3, // 4: facerec.FaceRecognition.Extract:output_type -> facerec.ExtractResponse
	5, // 5: facerec.FaceRecognition.Compare:output_type -> facerec.CompareResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_facerec_proto_init() }
func file_facerec_proto_init() {
	if File_facerec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_facerec_proto_rawDesc), len(file_facerec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_facerec_proto_goTypes,
		DependencyIndexes: file_facerec_proto_depIdxs,
		MessageInfos:      file_facerec_proto_msgTypes,
	}.Build()
	File_facerec_proto = out.File
	file_facerec_proto_goTypes = nil
	file_facerec_proto_depIdxs = nil
}
