// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: facerec.proto

package facerec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FaceRecognition_Extract_FullMethodName = "/facerec.FaceRecognition/Extract"
	FaceRecognition_Compare_FullMethodName = "/facerec.FaceRecognition/Compare"
)

// FaceRecognitionClient is the client API for FaceRecognition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaceRecognitionClient interface {
	Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
	Compare(ctx context.Context, in *CompareRequest, opts ...grpc.CallOption) (*CompareResponse, error)
}

type faceRecognitionClient struct {
	cc grpc.ClientConnInterface
}

func NewFaceRecognitionClient(cc grpc.ClientConnInterface) FaceRecognitionClient {
	return &faceRecognitionClient{cc}
}

func (c *faceRecognitionClient) Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, FaceRecognition_Extract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceRecognitionClient) Compare(ctx context.Context, in *CompareRequest, opts ...grpc.CallOption) (*CompareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareResponse)
	err := c.cc.Invoke(ctx, FaceRecognition_Compare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaceRecognitionServer is the server API for FaceRecognition service.
// All implementations must embed UnimplementedFaceRecognitionServer
// for forward compatibility.
type FaceRecognitionServer interface {
	Extract(context.Context, *ExtractRequest) (*ExtractResponse, error)
	Compare(context.Context, *CompareRequest) (*CompareResponse, error)
	mustEmbedUnimplementedFaceRecognitionServer()
}

// UnimplementedFaceRecognitionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFaceRecognitionServer struct{}

func (UnimplementedFaceRecognitionServer) Extract(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Extract not implemented")
}
func (UnimplementedFaceRecognitionServer) Compare(context.Context, *CompareRequest) (*CompareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compare not implemented")
}
func (UnimplementedFaceRecognitionServer) mustEmbedUnimplementedFaceRecognitionServer() {}
func (UnimplementedFaceRecognitionServer) testEmbeddedByValue()                         {}

// UnsafeFaceRecognitionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaceRecognitionServer will
// result in compilation errors.
type UnsafeFaceRecognitionServer interface {
	mustEmbedUnimplementedFaceRecognitionServer()
}

func RegisterFaceRecognitionServer(s grpc.ServiceRegistrar, srv FaceRecognitionServer) {
	// If the following call panics, it indicates UnimplementedFaceRecognitionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FaceRecognition_ServiceDesc, srv)
}

func _FaceRecognition_Extract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServer).Extract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceRecognition_Extract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServer).Extract(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceRecognition_Compare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecognitionServer).Compare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceRecognition_Compare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecognitionServer).Compare(ctx, req.(*CompareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FaceRecognition_ServiceDesc is the grpc.ServiceDesc for FaceRecognition service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaceRecognition_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "facerec.FaceRecognition",
	HandlerType: (*FaceRecognitionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Extract",
			Handler:    _FaceRecognition_Extract_Handler,
		},
		{
			MethodName: "Compare",
			Handler:    _FaceRecognition_Compare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "facerec.proto",
}
